name: CI-CD-Pipeline

on:
  push:
    - development

jobs:
  build-image-api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    defaults:
      run:
        working-directory: src
    env:
      REGION: us-east1
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo $GOOGLE_CREDENTIALS | docker login -u "_json_key" --password-stdin "https://${{ env.REGION }}-docker.pkg.dev"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGION }}-docker.pkg.dev/gaggar-dev/cloud-bootcamp/api
          tags: |
            type=sha
      - name: Build the Docker image for api
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./api.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    outputs:
      image: ${{ steps.meta.outputs.tags }}

  build-image-app:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    defaults:
      run:
        working-directory: src
    env:
      REGION: us-east1
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo $GOOGLE_CREDENTIALS | docker login -u "_json_key" --password-stdin "https://${{ env.REGION }}-docker.pkg.dev"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGION }}-docker.pkg.dev/gaggar-dev/cloud-bootcamp/app
          tags: |
            type=sha
      - name: Build the Docker image for api
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./app.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    outputs:
      image: ${{ steps.meta.outputs.tags }}

  

  deploy-api:
    needs: [build-image-api, build-image-app]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    defaults:
      run:
        working-directory: terraform
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - run: terraform init
      - run: terraform validate
      - run: terraform plan -var="slack_webhook_url=$SLACK_WEBHOOK"
      - run: terraform apply -var="slack_webhook_url=$SLACK_WEBHOOK" -auto-approve

